### ISSUE TITLE
2 ngAutocomplete on the same page ?

### ISSUE THREAD

**Issue by banibanc** [sengirab/ngAutocomplete#10]
Hi,

is it possible to have 2 ng autocomplete on the same page when they are filled from http source ?

If yes, how can I do that ? 

Great plugin by the way.

Thanks !

**Comment by sengirab** [comment]
Hi, it is possible.

You could create just one auto completer group, the only downside to this is. They will be rendered next to each other.

If you mean to use the completers on two different locations, you will need to create two groups.
Every item in a auto completer group is "fillable" by a datasource.

Thanks a lot!

**Comment by banibanc** [comment]
Hi,

I've tried this : 

`
@ViewChild(NgAutocompleteComponent) public completer: NgAutocompleteComponent;
@ViewChild(NgAutocompleteComponent) public completerLoc: NgAutocompleteComponent;
`

`products = [
        CreateNewAutocompleteGroup(
            'Search / choose in / from list',
            'completer',
            [],
            {titleKey: 'title', childrenKey: null}
        ),
    ];`
`
    locations = [
        CreateNewAutocompleteGroup(
            'Search / choose in / from list',
            'completerLoc',
            [],
            {titleKey: 'name', childrenKey: null}
        ),
    ];`

`<ng-autocomplete (keyup)="searchLocations($event)" (selected)="addLocation($event)" [classes]="['']" [group]="locations"></ng-autocomplete>
<ng-autocomplete (keyup)="searchProducts($event)" (selected)="selectProduct($event)" [classes]="['']" [group]="products"></ng-autocomplete>`

The first one is working but the second one fires that error : 

`TypeError: completer.group is undefined`

Can you tell me how I can it make it work ?

Thanks

**Comment by sengirab** [comment]
Could you provide me the function where these are called?

**Comment by banibanc** [comment]
For the first one : 
```
searchLocations(event: any) {
        if (event.target.value.length > 2) {
            this.customersService.getAllCustomers(localStorage.getItem('applicationId'), event.target.value, 1, 1000)
                .subscribe(resp => {
                    this.completerLoc.SetValues(
                        'completerLoc',
                        resp.locations
                    );
                });
        }
    }
```
For the second one : 
```
searchProducts(event: any) {
        if (event.target.value.length > 2) {
            this.catalogService.searchItem(localStorage.getItem('applicationId'), event.target.value, true)
                .subscribe(resp => {
                    this.completer.SetValues(
                        'completer',
                        resp.items
                    );
                });
        }
    }
```

**Comment by sengirab** [comment]
Yea, i mean the caller, like;

```
function iAmTheCaller() {
    this.searchProducts();
    this. searchLocations();
}
```

**Comment by banibanc** [comment]
If I deactivate the keyup I don't have the error message, you're right.
Where do I need to add your code ?

Do I still need to declare this twice ?

`@ViewChild(NgAutocompleteComponent) public completer: NgAutocompleteComponent; @ViewChild(NgAutocompleteComponent) public completerLoc: NgAutocompleteComponent;`

**Comment by sengirab** [comment]
Could you sent me a screenshot of the error in the console?

**Comment by banibanc** [comment]
![2018-04-06_155601](https://user-images.githubusercontent.com/5338661/38425017-0f172218-39b3-11e8-904a-8c6db848e17d.png)

**Comment by sengirab** [comment]
Line of the package code:
@ViewChildren(CompleterComponent) public completers: QueryList<CompleterComponent>;

It can only be undefined if its not set by the user. I really need some more code te really see how it's working. You can just mail me some screenshots of the html and typescript code, if you don't want screenshots of it here.

**Comment by banibanc** [comment]
I sent you the files by mail.
