### ISSUE TITLE
KeyUp not working on mobile

### ISSUE THREAD

**Issue by Swoox** [sengirab/ngAutocomplete#2]
I just implemented your newest version and noticed when I search on my mobile the search not update on keyUp or down.
If go to another input field it update, but this is not what I want.
![screenshot_2017-08-28-16-16-50](https://user-images.githubusercontent.com/22318636/29777580-d92ec358-8c0c-11e7-9eb5-52edd9491835.png)

**Comment by sengirab** [comment]
I'll check this out tomorrow!

**Comment by Swoox** [comment]
Ohh it's on an Andriod Galaxy s4.
 I will check if the same behaviour also goes for Iphone (not that I think it matter).

**Comment by Swoox** [comment]
Little update if selected an item first and hit backspace it works fine.

**Comment by sengirab** [comment]
<img width="601" alt="screen shot 2017-08-29 at 3 40 58 pm" src="https://user-images.githubusercontent.com/15229540/29823975-84809c04-8cd0-11e7-9123-1ffe475ab9e3.png">
<img width="600" alt="screen shot 2017-08-29 at 3 40 48 pm" src="https://user-images.githubusercontent.com/15229540/29823976-84998296-8cd0-11e7-9ab2-5add52e39e6d.png">

Seems to be working fine (simulator iphone)

**Comment by Swoox** [comment]
Did you hit searchbar and started typing?

**Comment by sengirab** [comment]
Yea. Just a click, started typing.. Worked

**Comment by Swoox** [comment]
Let me try another browser quickly using chrome.

**Comment by Swoox** [comment]
You using emulator with phone keyboard?
If I hit a key and remove phone keyboard it search.

**Comment by sengirab** [comment]
Yes i'm using the emulator with phone keyboard. Works when first key is tapped...

**Comment by Swoox** [comment]
Can try in Andriod?

**Comment by sengirab** [comment]
Just tested on Android.. Seems to be working fine.

You're just focussing and then tapping on a letter, right?

**Comment by Swoox** [comment]
Yeah also not work on another phone HTC.

**Comment by sengirab** [comment]
Tested on a Samsung, Chrome. Android 6.0.1.

Could you post your implementation.. Typescript code, package version?

**Comment by Swoox** [comment]
Using Anuglar v4.3.1.
Typescript v2.3.2
I use webpack to build in dev and prod.

In my component.
`    @ViewChild(NgAutocompleteComponent) public completer: NgAutocompleteComponent;

    public group = [
        CreateNewAutocompleteGroup(
            'Zoek of selecteer plaats',
            'completer',
            [
                { title: 'Groningen', id: '1' },
                { title: 'Amsterdam', id: '2' },
                { title: 'Alkmaar', id: '3' },
                { title: 'Groenlo', id: '4' },
                { title: 'Amersfoort', id: '5' },
            ],
            { titleKey: 'title', childrenKey: null },
            ''
        )
    ];`
In HTML
`<td><ng-autocomplete [classes]="['']" [group]="group"></ng-autocomplete></td>`

**Comment by sengirab** [comment]
Tested within same environment, cant seem to reproduce...
