### ISSUE TITLE
Adding parent child autocomplete html side code

### ISSUE THREAD

**Issue by donajoshy** [sengirab/ngAutocomplete#20]
Please add the code for parent child example

**Comment by sengirab** [comment]
https://github.com/sengirab/ngAutocomplete#user-content-with-children

**Comment by donajoshy** [comment]
i added this code but child not working according to the parent id

**Comment by sengirab** [comment]
Could you provide me your code?

**Comment by donajoshy** [comment]
<div>
    <ng-autocomplete (selected)="Selected($event)" [classes]="['fifty']"
                     [group]="group1" [key]="'group1'"></ng-autocomplete>
    <div style="clear: both;"></div>
</div>


 public group1 = [
    CreateNewAutocompleteGroup(
        'Search / choose in / from list',
        'completer_one',
        [
            {
                title: 'Option 1', id: '1',
                children: [
                    {title: 'Option 1', id: '1'},
                    {title: 'Option 2', id: '2'}
                ]
            },
            {
                title: 'Option 2', id: '2',
                children: [
                    {title: 'Option 3', id: '3'},
                    {title: 'Option 4', id: '4'}
                ]
            },
            {
                title: 'Option 3', id: '3',
                children: [
                    {title: 'Option 5', id: '5'},
                    {title: 'Option 6', id: '6'}
                ]
            },
        ],
        {titleKey: 'title', childrenKey: 'children'},
        ''
    ),
    CreateNewAutocompleteGroup(
        'Search / choose in / from list',
        'completer_two',
        [
            {title: 'Option 1', id: '1'},
            {title: 'Option 2', id: '2'},
            {title: 'Option 3', id: '3'},
            {title: 'Option 4', id: '4'},
            {title: 'Option 5', id: '5'},
            {title: 'Option 6', id: '6'},
        ],
        {titleKey: 'title', childrenKey: null},
        'completer_one'
    )
];

after selecting one from  parent,  not get the value corresponding  to parent id

**Comment by sengirab** [comment]
It should be setting the children it has. And also emitting the chosen value. Could you provide me with console.log's?
