### ISSUE TITLE
it's incompatible with angular version 4

### ISSUE THREAD

**Issue by mohsensrmst** [sengirab/ngAutocomplete#5]
hi 
I use angular version 4.3.6 and do all guide you said in document but when run project get this error:
`GET http://localhost:2634/node_modules/ng-auto-complete/ 403 (Forbidden)
Error: Fetch error: 403 Forbidden
  Instantiating http://localhost:2634/node_modules/ng-auto-complete
  Loading http://localhost:2634/app/app.module.js
  Loading ../app
    at system.src.js:1479
    at ZoneDelegate.invoke (zone.js:392)
    at Zone.run (zone.js:142)
    at zone.js:844
    at ZoneDelegate.invokeTask (zone.js:425)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at <anonymous>`

**Comment by bhavin9695** [comment]
same for me . i am using 4.2.4.

npm WARN ng-auto-complete@2.7.13 requires a peer of @angular/core@^2.4.0 || ^4.0.0 but none was installed.
npm WARN ng-auto-complete@2.7.13 requires a peer of @angular/compiler@^2.4.0 || ^4.0.0 but none was installed.
npm WARN ng-auto-complete@2.7.13 requires a peer of @angular/common@^2.4.0 || ^4.0.0 but none was installed.
npm WARN ng-auto-complete@2.7.13 requires a peer of rxjs@^5.0.1 but none was installed.

**Comment by sengirab** [comment]
Hi. I'll update the package soon to fix this error. It's just a warning for now, should be fine to use on angular 4 and above.
