### ISSUE TITLE
Data source from HTTP

### ISSUE THREAD

**Issue by snigdhakeerthisuram** [sengirab/ngAutocomplete#8]
I am trying the get the array or data source from a http and assigning it to the the autoomplete component but it is showing empty values but I could console my data source which is asigned.

public users = [
        CreateNewAutocompleteGroup(
            'Select user',
            'completer',
            this.employees,
            {titleKey: 'fullName', childrenKey: null}
        ),
    ];

ngOnInit() {
	this.http.get("rest url").subscribe(
		  (res: Response) => {
			  console.log(res.json())
			this.employees = res.json();
			}
		);
console.log(this.employees);
  }

**Comment by sengirab** [comment]
Hey. It's not possible (yet) to pass a datasource in such as observables or promises.

Current way to bypass this is:

```
@ViewChild(NgAutocompleteComponent) public completer: NgAutocompleteComponent;

ngOnInit() {
   this.http.get("rest url").subscribe((res: Response) => {
      this.employees = res.json();
      this.completer.SetValues(
          'completer',
          this.employees
      )
   });
}
```

**Comment by banibanc** [comment]
Hi,

I tried the way you posted but I get this error : 

"can't convert undefined to object"

Even if I try to set values like this : 

searchProducts(event: any) {
        if (event.target.value.length > 2) {
            this.catalogService.searchItem(localStorage.getItem('applicationId'), event.target.value, true)
                .subscribe(resp => {
                    this.products = resp.items;
                    this.completer.SetValues(
                        'completer',
                        // this.products
                        [
                            {title: 'product 1', id: 15},
                            {title: 'product 2', id: 25}
                        ]
                    );
                });
        }
    }

**Comment by snigdhakeerthisuram** [comment]
Hi,


I am trying to pre-select the autocomplete item by the below way. 

[
            {title: 'Option 1', id: '1'},
            {title: 'Option 2', id: '2'},
            {title: 'Option 3', id: '3'},
            {title: 'Option 4', id: '4'},
            {title: 'Option 5', id: '5'},
        ]
Is there any way that it could work if id and title are same as it is not allowing me to preselect on title base.

I mean in the below way
[
            {title: 'Option 1', id: 'Option 1'},
            {title: 'Option 2', id: 'Option 2'},
            {title: 'Option 3', id: 'Option  3'},
            {title: 'Option 4', id: 'Option  4'},
            {title: 'Option 5', id: 'Option  5'},
        ]

Using the below statement to preselect:
const completer = NgAutocompleteComponent.FindCompleter('aplicationType', this.completers);
completer.SelectItem('completer', '1');

Which selects "Option 1" on page load.
